### ISSUE TITLE
RollBar - I can't compile in iOS: 'React/RCTConvert.h' file not found 

### ISSUE THREAD

**Issue by javi10823** [rollbar/rollbar-react-native#60]
I'm receive this error:

'React/RCTConvert.h' file not found 

I follow all the instructions in the readme.

/node_modules/rollbar-react-native/ios/RollbarReactNative.m:2:9: fatal error: 'React/RCTConvert.h' file not found
#import <React/RCTConvert.h>
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by jessewgibbs** [comment]
@javi10823 sorry to hear you're encountering this issue.

@rokob any suggested for troubleshooting this?

**Comment by rokob** [comment]
This is in an existing react native app? The React libraries should be found by the peer react native dependency. What version of react native is this with?

**Comment by disseminate** [comment]
Getting this issue too on RN 0.57.3

**Comment by javi10823** [comment]
> This is in an existing react native app? The React libraries should be found by the peer react native dependency. What version of react native is this with?

**react-native-cli: 2.0.1
react-native: 0.55.4**

**Comment by jaimeagudo** [comment]
Any updates on this ? I am experiencing the same using CocoPods

```
    "rollbar-react-native": "^0.3.3",
    "react-native": "0.57.3",
```

The manual way in the other hand moans about 

`#import "Rollbar.h"`

 on `AppDelegate.m`

**Comment by gusgard** [comment]
Same with `0.57.5`! Any fast workaround? @rokob

**Comment by rokob** [comment]
Does this work with Rollbar version 0.3.1? I think the issue snuck in with 0.3.3 but I'm trying to bisect without being able to reliably reproduce this build issue.

**Comment by gusgard** [comment]
@rokob I tried it but I didn't have luck, Are you testing with Xcode `10.1`? In Appcenter with version `9.4.1` seems to work fine.

**Comment by jaimeagudo** [comment]
Yes Xcode 10.1 in my case
Jaime

**Comment by jaimeagudo** [comment]
This was the fix on the same issue for a different library, I tried to apply it tweaking the `HEADER_SEARCH_PATHS` of the Rollbar target within my own project with no luck though 

https://github.com/DylanVann/react-native-fast-image/pull/111/commits/f2043591bfac863822af6ad94456c4bada3d93cf

**Comment by rokob** [comment]
Okay I was running 3 different versions of Xcode but they are all less than 10, I'm getting 10.1 now and will see what's up.

**Comment by rokob** [comment]
Okay well the Xcode version wasn't it.

```
$ react-native info

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 624.69 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.3.0 - /usr/local/bin/node
      Yarn: 1.0.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 25.0.0, 25.0.3, 26.0.0, 26.0.2, 27.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2.3 AI-162.3934792
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

I did `react-native init RNAwesome`, ran `yarn add rollbar-react-native`, so my `package.json` looks like:
```
{
  "name": "RNAwesome",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "rollbar-react-native": "^0.3.3"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I edited the generated `App.js`:
```
 10 import {Button, Platform, StyleSheet, Text, View} from 'react-native';
...

 12 import { Client } from 'rollbar-react-native'
 13 const rollbar = new Client('my access token');
...
 22 const callit = function() {
 23   rollbar.error(new Error('Hello, React Native'))
 24 };
...
 34         <Button
 35           onPress={ callit }
 36           title="Call Rollbar"
 37           color="#CC2222"
 38         />
```

I ran:
```
$ yarn
$ react-native link rollbar-react-native
$ react-native run-ios
```

After mountains of compiler output, the build succeeds, the simulator opens, I tap the button and get an item in Rollbar.

**Comment by rokob** [comment]
So the only thing I am seeing different with the posted info is that I am still on 10.13, I can't believe that would be the issue but I am going to upgrade to 10.14 and try again. There are some things with underlying rollbar-ios library that could be an issue so I am going to try some things over there and update the submodule.

**Comment by jaimeagudo** [comment]
Finally fixed the original error on `0.3.3`, https://github.com/rollbar/rollbar-react-native/issues/16#issuecomment-440237013  feel free to close this one, thanks @rokob

**Comment by rokob** [comment]
That is weird because `react-native link rollbar-react-native` to a new project makes the following change:

```
HEADER_SEARCH_PATHS = (
           "$(inherited)",
           "$(SRCROOT)/../node_modules/rollbar-react-native/ios/**",
         );
```

**Comment by rokob** [comment]
So the command `react-native link rollbar-react-native` might be broken in some settings (which would be a react-native problem which would not surprise me) or one might forget to run it, but the underlying library hasn't changed to make this not work.
